name: Publish to npm

on:
  # O workflow será acionado SEMPRE que uma nova tag for PUSHED
  # O padrão de tags (tags-ignore) 'v*.*.*' é essencial para pegar tags de versão como 'v1.0.0'
  create:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    # O job só deve rodar se o nome da tag (o 'ref') começar com 'v'
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    # Define as permissões
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use sua versão de preferência
          # O 'registry-url' é crucial para a autenticação no NPM
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        # Use `npm ci` para uma instalação limpa e rápida
        run: npm ci 
        
      # === Etapa Opcional: Build/Compilação ===
      # Se o seu pacote precisar ser compilado antes de ser publicado (Ex: TypeScript)
      # Adicione seu comando de build aqui. Exemplo:
      # - name: Build package
      #   run: npm run build
          
      - name: Publish to NPM
        # O comando `npm publish` irá usar o `package.json` para publicar a versão
        run: npm publish --access public
        env:
          # Usa o segredo do GitHub para autenticar no NPM
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}